Dans le dossier de mon système de recommandation, j'ai le dossier models dans lequel il y a le fichier pme_model.py qui a pour contenu: from pymongo import MongoClient from bson import ObjectId  class PMEModel:     def __init__(self, db_uri="mongodb://localhost:27017/", db_name="SMEdb"):         # Connexion à MongoDB         self.client = MongoClient(db_uri)         self.db = self.client[db_name]         self.collection = self.db['pmes']      def find_by_id(self, pme_id):         # Convertir l'ID en ObjectId et rechercher dans la base de données         return self.collection.find_one({"_id": ObjectId(pme_id)})      def find_all_except(self, pme_id):         # Rechercher toutes les PMEs sauf celle avec pme_id         return self.collection.find({"_id": {"$ne": ObjectId(pme_id)}})  pme_model = PMEModel() Dans le même dossier de recommandation j'ai le dossier recommandation qui a le fichier recommandation_engine.py qui a pour extrait de contenu : from bson import ObjectId import numpy as np #import sys #sys.path.append('./../models/pme_model.py')  # Ajouter le chemin vers les modèles from models.pme_model import pme_model. J'ai ce pendant l'erreur /recommandation/recommandation_engine.py", line 5, in 
    from models.pme_model import pme_model
ModuleNotFoundError: No module named 'models'. Donnes en la cause et donne la solution à ce problème.